spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/techstore
    username: postgres
    password: admin123

  data:
    web:
      page-serialization-mode: via-dto

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true

          starttls:
            enable: true
            required: false

          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

admin:
  email: admin@pcbyte.cl
  password: Cambiar123!

mercadopago:
  access:
    token: ${MP_ACCESS_TOKEN}

app:
  base-url: https://unrarefied-unpervasive-pandora.ngrok-free.dev

  frontend-url: http://192.168.100.226:5173

  verification:
    max-requests-per-hour: 5
    resend-cooldown-seconds: 60
    email-verification-expiration-hours: 24
    guest-checkout-expiration-minutes: 10
    guest-account-conversion-expiration-hours: 1
    password-reset-expiration-minutes: 30

  mail:
    from-address: no-reply@pcbyte.cl
    from-name: PCByte Store
    reply-to: contacto@pcbyte.cl

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}