CREATE TABLE IF NOT EXISTS brands (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    logo_url VARCHAR(500),
    website VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE
);