ALTER TABLE products
ADD COLUMN IF NOT EXISTS internal_code VARCHAR(30);

ALTER TABLE products
ADD COLUMN IF NOT EXISTS sku VARCHAR(100);

ALTER TABLE products
ADD COLUMN IF NOT EXISTS mpn VARCHAR(100);

ALTER TABLE products
ADD COLUMN IF NOT EXISTS specifications TEXT;

ALTER TABLE products
ADD COLUMN IF NOT EXISTS warranty TEXT;

ALTER TABLE products
ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE products
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE products
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;